### PR TITLE
Start to Theme Oomph Paragraph Components

### PR DESCRIPTION
**Pull request by jhogue**
Add SCSS/SASS files to the module folder structure and start the structure for styling Oomph Paragraph components. The new `oomph_paragraphs.libraries/yml` is used to store which CSS files are needed by which component, and each twig file "attaches" the needed library to it. 

So far, here is what I have been thinking: 
* Each component uses a "general" CSS file as its `base` (in oomph_paragraphs.libraries.yml)
* Each component also uses a `component` level CSS file
* This should allow a `theme`-level file to override what is needed later by other authors

The SCSS structure: 
* An `abstracts` folder for variables, mixins
* A `fields` folder for individual adminnable fields, like background color
* A `vendor` folder to be clear about what other code we are using and therefore, not responsible for, or, have to keep an eye on for updates/bug fixes
* Each component file (top level, no underscore in the name) pulls in the elements that it needs, according to which field customizations are available to an admin author

### CODE REVIEW

**Comment by johncionci** [comment]
@jhogue 

First big question is, are we making this to be BS dependent or no? I would say that it should be general enough to be used on non BS projects ie BCBS.com?

**Comment by johncionci** [comment]
So at a high level I believe we should have a set of global vars and local (component) vars. So vars for the image component live with the image component are consolidated with the image component.

If we are requiring something like the animate library then that via dependency manager so we wouldn't need to include that in the repo, therefore we may be able to trash the `vendor` folder.

Same for the BS stuff, somehow we need to extrapolate that out but not sure how at the moment, would most likely need to add to a project and test.

I would change the `theme` file to the `variables` file because 1. thats all we have in there 2. we may have a `theme` file in the actual theme that the module is being used.

In that file we need to make all the vars `! default` so we can override them later in the actual theme if needed.

**Comment by jhogue** [comment]
@johncionci I started those requests. More to come. Using the `$global__` and `$local__` BEM style convention for variables. 

Not sure what to do with the Vendor stuff yet. I needed to edit the way the Animations work, so technically, while these were sourced from a vendor, I made changes so I should not store them in the vendor folder anymore anyway. And again, we do not need the entire BS4 library to get this to work, nor do we want to include ALL those styles… so I'll want to be careful about how we bring that in or require it.

**Comment by jhogue** [comment]
Animations will not work yet because we have them in the wrong place (in the admin config). Towards the end of the recent client project, Pico moved them (at our request) from the row to the individual component. 

I say that we get this stuff merged, and then tackle an update to the Config for animations as well as the supporting CSS in a new branch. 

CC: @nathandentzau

**Pull request merged**
